# Generated by Django 3.2.9 on 2021-11-24 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id_machine', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField(null=True, verbose_name='user_id')),
                ('city', models.CharField(max_length=50, null=True, verbose_name='City')),
                ('address', models.CharField(max_length=200, null=True, verbose_name='Address')),
                ('type_machine', models.CharField(choices=[(0, 'Granos'), (1, 'Granos chicos'), (2, 'Mayor capacidad'), (3, 'Maquina estandar')], max_length=50, null=True, verbose_name='Machine_type')),
                ('date_create', models.DateField(auto_now_add=True, verbose_name='Date_create')),
                ('is_activate', models.BooleanField(default=True, verbose_name='Active Machine')),
                ('balance_machine', models.BigIntegerField(default=0, null=True)),
            ],
        ),
    ]
